"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { Archive,Eye,Pencil,Trash2,X } from "lucide-react";
import { deleteProductAction,setProductStatusAction } from "@/app/actions/admin.actions";

export function AdminProductActionsClient({id,slug,status}:{id:string;slug:string;status:string}){
 const [busy,setBusy]=useState(false),[open,setOpen]=useState(false),[error,setError]=useState<string|null>(null);const cancelRef=useRef<HTMLButtonElement>(null);const router=useRouter();
 useEffect(()=>{if(!open)return;cancelRef.current?.focus();const close=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy)setOpen(false)};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[open,busy]);
 const toggle=async()=>{setBusy(true);setError(null);const r=await setProductStatusAction(id,status==="ACTIVE"?"ARCHIVED":"ACTIVE");setBusy(false);if(!r.success)setError(r.error||"Unable to update status.");else router.refresh()};
 const remove=async()=>{setBusy(true);setError(null);const r=await deleteProductAction(id);setBusy(false);if(!r.success)setError(r.error||"Unable to deactivate product.");else{setOpen(false);router.refresh()}};
 return <div className="flex min-w-48 flex-col items-end gap-1"><div className="flex flex-wrap justify-end gap-2">{status==="ACTIVE"&&<Link href={`/products/${slug}`} className="inline-flex items-center gap-1 font-bold text-wine-800"><Eye className="h-3 w-3"/>Preview</Link>}<Link href={`/admin/products/${id}/edit`} className="inline-flex items-center gap-1 font-bold text-blue-700"><Pencil className="h-3 w-3"/>Edit</Link><button disabled={busy} onClick={toggle} className="inline-flex items-center gap-1 font-bold text-amber-700"><Archive className="h-3 w-3"/>{status==="ACTIVE"?"Archive":"Publish"}</button>{status!=="INACTIVE"&&<button disabled={busy} onClick={()=>setOpen(true)} className="inline-flex items-center gap-1 font-bold text-red-700"><Trash2 className="h-3 w-3"/>Delete</button>}</div>{error&&<span className="text-[10px] text-red-600">{error}</span>}{open&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/55 sm:items-center sm:p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><section role="alertdialog" aria-modal="true" aria-labelledby={`delete-${id}`} className="w-full rounded-t-2xl bg-white p-5 text-left shadow-2xl sm:max-w-md sm:rounded-2xl sm:p-6"><div className="flex justify-between gap-4"><div><h2 id={`delete-${id}`} className="font-serif text-xl font-bold text-wine-900">Deactivate this product?</h2><p className="mt-2 text-sm leading-6 text-stone-600">The product stays in the database with <strong>INACTIVE</strong> status and is hidden from customers. Stock and sales history remain available.</p></div><button aria-label="Close" onClick={()=>setOpen(false)}><X className="h-5 w-5"/></button></div><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button ref={cancelRef} disabled={busy} onClick={()=>setOpen(false)} className="min-h-11 rounded-lg border px-5 py-2.5 font-bold">Cancel</button><button disabled={busy} onClick={remove} className="min-h-11 rounded-lg bg-red-700 px-5 py-2.5 font-bold text-white">{busy?"Deactivating…":"Yes, deactivate product"}</button></div></section></div>}</div>;
}
