"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { updateProductAction } from "@/app/actions/admin.actions";

export function EditProductFormClient({ product, categories, brands }: { product: any; categories: Array<{id:string;name:string}>; brands: Array<{id:string;name:string}> }) {
  const variant = product.variants[0];
  const [form,setForm]=useState({name:product.name,slug:product.slug,sku:product.sku,variantSku:variant?.sku||`${product.sku}-VAR`,categoryId:product.categoryId,brandId:product.brandId||"",mrp:product.mrp,sellingPrice:product.sellingPrice,tax:product.tax,stock:variant?.inventory?.availableStock??variant?.stock??0,fabric:product.fabric||"",occasion:product.occasion||"",pattern:product.pattern||"",color:variant?.color||"",size:variant?.size||"Free Size",imageUrl:product.images[0]?.url||"",shortDescription:product.shortDescription||"",description:product.description,status:product.status,featured:product.featured,bestseller:product.bestseller,newArrival:product.newArrival});
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const router=useRouter();
  const set=(key:string,value:string|number|boolean)=>setForm((old)=>({...old,[key]:value}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError(null);const result=await updateProductAction(product.id,{name:form.name,slug:form.slug,sku:form.sku,description:form.description,shortDescription:form.shortDescription||undefined,categoryId:form.categoryId,brandId:form.brandId||undefined,mrp:Number(form.mrp),sellingPrice:Number(form.sellingPrice),tax:Number(form.tax),fabric:form.fabric||undefined,occasion:form.occasion||undefined,pattern:form.pattern||undefined,status:form.status,featured:form.featured,bestseller:form.bestseller,newArrival:form.newArrival,images:[{url:form.imageUrl,altText:form.name,isPrimary:true,sortOrder:1}],variants:[{sku:form.variantSku,color:form.color||undefined,size:form.size||undefined,fabric:form.fabric||undefined,price:Number(form.sellingPrice),stock:Number(form.stock)}]});setBusy(false);if(!result.success)setError(result.error||"Unable to update product.");else{router.push("/admin/products");router.refresh();}};
  const fields:Array<[keyof typeof form,string,string]>=[["name","Product title","text"],["slug","URL slug","text"],["sku","Product SKU","text"],["variantSku","Variant SKU","text"],["mrp","MRP (₹)","number"],["sellingPrice","Selling price (₹)","number"],["tax","Tax (%)","number"],["stock","Available stock","number"],["fabric","Fabric","text"],["occasion","Occasion","text"],["pattern","Pattern","text"],["color","Color","text"],["size","Size","text"],["imageUrl","Primary image URL","url"]];
  return <form onSubmit={submit} className="space-y-5 rounded-xl border border-stone-200 bg-white p-5 text-xs shadow-md sm:p-8"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{fields.map(([key,label,type])=><label key={key} className={`${key==="imageUrl"?"sm:col-span-2 ":""}font-bold text-stone-700`}>{label}<input required={!(["fabric","occasion","pattern","color","size"] as string[]).includes(key)} min={type==="number"?0:undefined} type={type} value={String(form[key])} onChange={(e)=>set(key,type==="number"?Number(e.target.value):e.target.value)} className="mt-1 w-full rounded border border-stone-300 px-3 py-2 font-normal"/></label>)}</div><div className="grid gap-4 sm:grid-cols-2"><label className="font-bold">Category<select value={form.categoryId} onChange={(e)=>set("categoryId",e.target.value)} className="mt-1 w-full rounded border p-2">{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="font-bold">Brand<select value={form.brandId} onChange={(e)=>set("brandId",e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">No brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><label className="block font-bold">Short description<input value={form.shortDescription} onChange={(e)=>set("shortDescription",e.target.value)} className="mt-1 w-full rounded border p-2 font-normal"/></label><label className="block font-bold">Detailed description<textarea required minLength={10} rows={5} value={form.description} onChange={(e)=>set("description",e.target.value)} className="mt-1 w-full rounded border p-2 font-normal"/></label><div className="flex flex-wrap gap-5">{[["featured","Featured"],["bestseller","Bestseller"],["newArrival","New arrival"]].map(([key,label])=><label key={key} className="flex gap-2 font-bold"><input type="checkbox" checked={Boolean(form[key as keyof typeof form])} onChange={(e)=>set(key,e.target.checked)}/>{label}</label>)}</div>{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded wine-gradient-bg py-3.5 font-bold uppercase text-gold-300 disabled:opacity-50">{busy?"Saving…":"Save Product Changes"}</button></form>;
}
